public class ControleEstoque {
    public static void main(String[] args) {
    
    String nameSmartphone = "K3000";
    String marcaSmartphone = "Naga";
    double precoSmartphone = 4500;
    int estoqueSmartphone = 50;
    
    
    String nameLaptop = "Zeus";
    String marcaLaptop = "Triton";
    double precoLaptop = 6000;
    int estoqueLaptop = 30;
    
    String nameFoneBluetooth = "Dragon";
    String marcaFoneBluetooth = "Naga";
    double precoFoneBluetooth = 300;
    int estoqueFoneBluetooth = 100;
    
    System.out.println("Dados do Smartphone:");
    System.out.println("Nome: " + nameSmartphone);
    System.out.println("Marca: " + marcaSmartphone);
    System.out.println("Preco: R$" + precoSmartphone);
    System.out.println("Estoque: " + estoqueSmartphone);
        
    System.out.println("Dados do LapTop:");
    System.out.println("Nome: " + nameLaptop);
    System.out.println("Marca: " + marcaLaptop);
    System.out.println("Preco: R$" + precoLaptop);
    System.out.println("Estoque: " + estoqueLaptop);   
    
    System.out.println("Dados do FoneBluetooth:");
    System.out.println("Nome: " + nameFoneBluetooth);
    System.out.println("Marca: " + marcaFoneBluetooth);
    System.out.println("Preco: R$" + precoFoneBluetooth);
    System.out.println("Estoque: " + estoqueFoneBluetooth); 
        
    }
       }
